### ISSUE TITLE
Add `expoPublished` backend endpoint

### ISSUE THREAD

**Issue by McIntireEvan** [gotechnica/technica-expo-app#109]
Add admin endpoints for getting and setting if the expo is published or not.

That is, create `/admin/published` with GET and POST handlers.

**Comment by McIntireEvan** [comment]
Turns out this exists and I didn't do my due diligence in checking - sorry! Might still be worth looking into if there's better naming or functionality.

Endpoint is `/api/is_published_status`, for reference. I'll leave this up to you how you want to proceed

**Comment by laurenkosub** [comment]
Since a breakpoint already exists, I am going to close this issue

**Comment by laurenkosub** [comment]
close #109

**Comment by laurenkosub** [comment]
Did you want the is_published_status flag to only be accessible by admins? As of right now it is under the public route and does not require authentication.

**Comment by thisistimothychen** [comment]
`is_published_status` should be available publicly since the frontend uses it to figure out whether or not to render the projects

**Comment by McIntireEvan** [comment]
Closing :)
