### ISSUE TITLE
Extend the Card Component to have an action

### ISSUE THREAD

**Issue by McIntireEvan** [gotechnica/technica-expo-app#118]
Building off of #117, add optional props to the `Card` component allowing an action name and action - like we see in `AdminSponsor` or `AdminWinner`, with the "hide" and "logout" buttons, respectively.

Then, with that component, replace one of the current custom cards (like the ones mentioned above) with this more generic implementation.

**Comment by Maosef** [comment]
see PR and 36df24a.

**Comment by McIntireEvan** [comment]
Closed by #120
