### ISSUE TITLE
Admin Page - Create & Edit Sponsor Modals

### ISSUE THREAD

**Issue by elangloi** [gotechnica/technica-expo-app#32]
Design a form for the modal body for creating a new sponsor in the admin page.
Design a form for the modal body for editing and deleting an existing sponsor in the admin page.

See the back end PRD for fields to include. Work with the backend team if any fields are unclear.

The create modal with all functionality should be built in /admin/CreateSponsorModal.js.
The edit modal with all functionality should be built in /admin/EditSponsorModal.js.

**Comment by ng-david** [comment]
nice work with this!
