### ISSUE TITLE
Investigate search bar options

### ISSUE THREAD

**Issue by ng-david** [gotechnica/technica-expo-app#35]
Currently the expo app uses a search bar, a dropdown of hacks, a dropdown of challenges on the '/' path.

I was wondering if we could replace this with a unified search the way the other expo app does? I think the dropdown of hacks is unnecessary given a search bar, and having a unified search would make it less tedious to filter by challenge :) 

Feel free to comment your thoughts below.

Example: https://bit.camp/expo/

**Comment by elangloi** [comment]
I agree with cutting the dropdown of hacks since it isn't doing any grouping but I think keeping a dropdown of challenges provides a quicker filter than searching for the challenge name, opinions on challenge drop down + text search? @ng-david

**Comment by ng-david** [comment]
I suppose both can't hurt, was just hoping to slimify the UI as much as
possible considering the old search bar method never got complaints

Unless it did? @Timothy Chen

**Comment by ng-david** [comment]
I suppose both can't hurt, was just hoping to slimify the UI as much as possible considering the old search bar method never got complaints

Unless it did? @timothychen01

**Comment by elangloi** [comment]
@ng-david @timothychen01 Are we still considering removing the challenge dropdown on home or could we close this issue?

**Comment by ng-david** [comment]
sounds closeable to me!
