### ISSUE TITLE
Explore better schema for defining challenge objects for projects when seeding

### ISSUE THREAD

**Issue by thisistimothychen** [gotechnica/technica-expo-app#45]
Currently, we use a pre-defined rule / make assumptions about how challenges will be named on Devpost (hyphenated as `Company Name - Awesome Challenge Name Here`). This is too hacky/hardcoded and may not be flexible enough.

Instead, a better approach may be to pull challenge info from the Sponsors DB and use string/regex matching against the CSV field.

**Comment by McIntireEvan** [comment]
As it stands, we have the devpost scraper, which scapes in the format CHALLENGE - COMPANY (n). The implementation also seems to be fairly robust, though it probably could be better tested.

I do think that this schema is at least good enough, and I don't really see a better standard way. Closing this issue.
