### ISSUE TITLE
UI Upgrades

### ISSUE THREAD

**Issue by timothychen01** [gotechnica/technica-expo-app#81]
## Things to fix:

Get rid of the "Company_Name's Challenges" and move clickable text to left?
![image.png](https://images.zenhubusercontent.com/5ae8e9ff4b5806bc2bd16338/1670380d-debb-44e0-8d93-8dc768986f9c)

**Comment by ng-david** [comment]
lmao i agree too, but let's make sure to low priority the admin until every other page is perfect :)

**Comment by timothychen01** [comment]
That makes sense!!!

**Comment by elangloi** [comment]
by move clickable text to the left, do you mean "create challenge" or all of the linkbuttons?

**Comment by elangloi** [comment]
another change to note here- for mobile responsiveness, we should make each panel collapsable / hide-able. currently, viewing on mobile requires you to go through all sponsors before reaching the project panel.
