### ISSUE TITLE
Add `expoPublished` state for admin to toggle

### ISSUE THREAD

**Issue by thisistimothychen** [gotechnica/technica-expo-app#97]
One thing we ran into right before expo was a few sponsors asked why they weren't seeing any projects yet. Adding a simple flag that could be used to show "pre-expo" messages would be very useful so that admin can seed projects, assign table numbers, manually make any necessary modifications, etc...

Messages can be in the effect of: `Hey there! We're currently adding all of the wonderful projects into our system and working on assigning table numbers for the expo. We'll update you when expo is about to begin!`

Approach: add a global variable (like `publish_winners` we currently have) and an endpoint to toggle this - which will be used in Godmode view

**Comment by McIntireEvan** [comment]
Creating separate task for the backend part of this. 

This task is just the frontend component.

**Comment by McIntireEvan** [comment]
Turns out this already exists - this task is now simply adjust the frontend to whatever changes are made in for #109

**Comment by McIntireEvan** [comment]
Closing :)
